### ISSUE TITLE
sandbox demo page breaks

### ISSUE THREAD

**Issue by paulirish** [echonest/remix.js#6]
https://echonest.github.io/remix/js/examples/sandbox-demo.html

All the API requests are over HTTP but Github forces the gh-page into SSL so yeah they fail.

Pretty sure all these endpoints support HTTPS but letting you confirm.

Cheers

**Comment by paulirish** [comment]
@bwhitman been a while! and thanks!

**Comment by bwhitman** [comment]
hah! hey paul!! sorry for the lag, we are cleaning this up for a move over to Spotify :)
